Importing libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df =  pd.read_csv("Dataset_1.csv")

In [5]:
df.head()

,accident_id,accident_datetime,state,district,area_type,latitude,longitude,road_type,road_condition,road_lighting,...,ambulance_called,police_called,response_time_minutes,hospitalization_required,num_vehicles,num_injuries,num_fatalities,accident_severity,insurance_claim_filed,insurance_claim_amount
0,ACC20240000709,2024-12-15 15:14:47,Karnataka,Hubli District,Rural,15.741067,74.555047,State Highway,Pothole-Ridden,Streetlight Absent,...,No,Yes,86.178166,Yes,2,3,1,Severe,No,NaN
1,ACC20200196249,2020-09-09 21:36:54,Haryana,Faridabad District,Urban,30.211127,75.461897,Other District Road,Dry,Streetlight Absent,...,No,No,NaN,No,2,0,0,Minor,Yes,26761.0
2,ACC20180059148,2018-07-24 16:43:57,West Bengal,Siliguri District,Semi-Urban,23.782972,86.281103,State Highway,Under Construction,Streetlight Absent,...,No,No,NaN,No,5,2,0,Moderate,Yes,9295.0
3,ACC20160076737,2016-11-17 17:53:16,West Bengal,Howrah District,Rural,24.872909,87.339504,National Highway,Dry,Streetlight Absent,...,Yes,Yes,16.943981,No,1,0,0,Minor,Yes,48147.0
4,ACC20230004919,2023-03-18 23:35:24,Rajasthan,Jodhpur District,Semi-Urban,24.305082,74.252979,State Highway,Dry,Streetlight Present,...,No,No,NaN,No,3,0,0,Minor,Yes,20636.0

In [6]:
df.shape

(202000, 48)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 202000 entries, 0 to 201999
Data columns (total 48 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   accident_id                202000 non-null  str
 1   accident_datetime          202000 non-null  str
 2   state                      202000 non-null  str
 3   district                   195938 non-null  str
 4   area_type                  202000 non-null  str
 5   latitude                   192022 non-null  float64
 6   longitude                  192022 non-null  float64
 7   road_type                  202000 non-null  str
 8   road_condition             202000 non-null  str
 9   road_lighting              195936 non-null  str
 10  number_of_lanes            193914 non-null  float64
 11  speed_limit_kmph           191888 non-null  float64
 12  estimated_speed_kmph       202000 non-null  float64
 13  junction_type              195935 non-null  str
 14  traffic_signal_present     193937 non-null  str
 15  median_present             193931 non-null  str
 16  weather_condition          197962 non-null  str
 17  visibility_km              189879 non-null  float64
 18  temperature_c              191903 non-null  float64
 19  rainfall_mm                202000 non-null  float64
 20  driver_age                 173756 non-null  float64
 21  driver_gender              195942 non-null  str
 22  driving_experience_years   173756 non-null  float64
 23  license_status             202000 non-null  str
 24  alcohol_involved           202000 non-null  str
 25  distraction_involved       202000 non-null  str
 26  mobile_phone_used          202000 non-null  str
 27  fatigue_involved           202000 non-null  str
 28  helmet_seatbelt_used       202000 non-null  str
 29  vehicle_type               202000 non-null  str
 30  vehicle_age_years          173756 non-null  float64
 31  vehicle_brand              163334 non-null  str
 32  vehicle_model              158059 non-null  str
 33  vehicle_condition          202000 non-null  str
 34  overloading_status         191891 non-null  str
 35  primary_cause              202000 non-null  str
 36  secondary_cause            62925 non-null   str
 37  emergency_services_called  202000 non-null  str
 38  ambulance_called           202000 non-null  str
 39  police_called              202000 non-null  str
 40  response_time_minutes      96227 non-null   float64
 41  hospitalization_required   193928 non-null  str
 42  num_vehicles               202000 non-null  int64
 43  num_injuries               202000 non-null  int64
 44  num_fatalities             202000 non-null  int64
 45  accident_severity          202000 non-null  str
 46  insurance_claim_filed      202000 non-null  str
 47  insurance_claim_amount     91096 non-null   float64
dtypes: float64(13), int64(3), str(32)
memory usage: 119.3 MB

In [8]:
df.duplicated().sum()

980

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(201020, 48)

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,191084.0,21.761686,8.746626,-89.993206,17.833633,23.359781,26.643660,89.967149
longitude,191084.0,77.980009,15.199619,-179.316379,75.582829,77.914638,82.084662,179.807326
number_of_lanes,192974.0,2.847715,1.421421,1.000000,2.000000,2.000000,4.000000,6.000000
speed_limit_kmph,190952.0,58.829287,23.127486,20.000000,40.000000,60.000000,70.000000,120.000000
estimated_speed_kmph,201020.0,61.665766,29.595935,5.000000,39.900000,57.300000,78.200000,160.000000
visibility_km,188963.0,4.912544,2.851271,0.020000,2.660000,4.700000,7.360000,10.850000
temperature_c,190971.0,22.200665,8.148013,2.000000,15.600000,22.300000,28.800000,47.000000
rainfall_mm,201020.0,3.488557,10.438547,0.000000,0.000000,0.000000,0.000000,252.100000
driver_age,173064.0,36.481735,12.819477,13.000000,27.000000,36.000000,45.000000,102.000000
driving_experience_years,173064.0,16.723991,11.906184,0.000000,7.100000,16.000000,24.900000,55.000000
vehicle_age_years,173064.0,5.481578,5.391930,0.000000,1.600000,3.800000,7.600000,30.000000
response_time_minutes,95765.0,21.921039,19.088520,2.000000,7.348035,17.658348,30.055183,180.000000
num_vehicles,201020.0,2.536384,1.457741,1.000000,2.000000,2.000000,3.000000,24.000000
num_injuries,201020.0,1.083678,1.401712,0.000000,0.000000,1.000000,2.000000,13.000000
num_fatalities,201020.0,0.120366,0.531497,-1.000000,0.000000,0.000000,0.000000,15.000000
insurance_claim_amount,90749.0,41105.165412,38275.352139,3000.000000,13906.000000,29463.000000,55823.000000,434334.000000

In [14]:
df.describe(include='object').T

C:\Users\pushk\AppData\Local\Temp\ipykernel_13556\1760094569.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object').T

                            count  unique                  top    freq
accident_id                201020  200000       ACC20180059148       2
accident_datetime          201020  199922  2018-07-24 16:43:57       2
state                      201020      21        Uttar Pradesh   28645
district                   194988      87      Kanpur District    4707
area_type                  201020       3                Urban   90630
road_type                  201020      20  Other District Road   54001
road_condition             201020       5                  Dry  124507
road_lighting              194987       2  Streetlight Present  116916
junction_type              194986       6          No Junction   68148
traffic_signal_present     192988       8                   No  118740
median_present             192989       8                   No  109684
weather_condition          197002      21                Clear  108774
driver_gender              194990       3                 Male  148535
license_status             201020       5                Valid  117731
alcohol_involved           201020       3                   No  143098
distraction_involved       201020       3                   No  137295
mobile_phone_used          201020       9                   No  143213
fatigue_involved           201020       3                   No  161233
helmet_seatbelt_used       201020       3       Not Applicable   84473
vehicle_type               201020       8          Two-Wheeler   76433
vehicle_brand              162684      20                Honda   17270
vehicle_model              157432      50              Jupiter    5909
vehicle_condition          201020       4                 Good   88766
overloading_status         190970       4       Not Applicable  156442
primary_cause              201020      13              Weather   26292
secondary_cause             62630      13         Overspeeding    9721
emergency_services_called  201020       2                   No  105255
ambulance_called           201020       2                   No  139653
police_called              201020       2                   No  119682
hospitalization_required   192980       2                   No  137531
accident_severity          201020       4                Minor  110536
insurance_claim_filed      201020       3                  Yes   95419

In [16]:
num_cols = df.describe().columns
non_num_cols = df.drop(num_cols,axis=1).columns
len(num_cols),len(non_num_cols)

(16, 32)

In [17]:
print(num_cols)
print(non_num_cols)

Index(['latitude', 'longitude', 'number_of_lanes', 'speed_limit_kmph',
       'estimated_speed_kmph', 'visibility_km', 'temperature_c', 'rainfall_mm',
       'driver_age', 'driving_experience_years', 'vehicle_age_years',
       'response_time_minutes', 'num_vehicles', 'num_injuries',
       'num_fatalities', 'insurance_claim_amount'],
      dtype='str')
Index(['accident_id', 'accident_datetime', 'state', 'district', 'area_type',
       'road_type', 'road_condition', 'road_lighting', 'junction_type',
       'traffic_signal_present', 'median_present', 'weather_condition',
       'driver_gender', 'license_status', 'alcohol_involved',
       'distraction_involved', 'mobile_phone_used', 'fatigue_involved',
       'helmet_seatbelt_used', 'vehicle_type', 'vehicle_brand',
       'vehicle_model', 'vehicle_condition', 'overloading_status',
       'primary_cause', 'secondary_cause', 'emergency_services_called',
       'ambulance_called', 'police_called', 'hospitalization_required',
       'accident_severity', 'insurance_claim_filed'],
      dtype='str')